name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.11

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff linter
        run: uv run ruff check .

      - name: Run Ruff formatter
        run: uv run ruff format --check .

      - name: Type check with mypy
        run: uv run mypy . --ignore-missing-imports

      - name: Run tests
        run: uv run pytest

      - name: Check security with bandit
        run: uv run bandit -r app/

      - name: Test application startup
        run: |
          uv run python -c "from app.main import app; print('✅ Application imports successfully')"
