name: Ruff

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      working-directory: ./src
      run: poetry install --only=dev
    
    - name: Run Ruff linter
      working-directory: ./src
      run: poetry run ruff check .
    
    - name: Run Ruff formatter
      working-directory: ./src
      run: poetry run ruff format --check .